# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc ""
  homepage "https://devx.stakpak.dev/"
  version "0.4.35"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stakpak/devx/releases/download/v0.4.35/devx_Darwin_arm64.tar.gz"
      sha256 "3d09b558fcb3fed08996927ea13ffe272505263bf519039ca32a12d8f6420974"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stakpak/devx/releases/download/v0.4.35/devx_Darwin_x86_64.tar.gz"
      sha256 "5dacf16242fa22a39d973e61b6db2d09197665aa9fbeeab9b57039d0179deb65"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stakpak/devx/releases/download/v0.4.35/devx_Linux_arm64.tar.gz"
      sha256 "0be5e9ceb32c49d495e7e667cb3e0c18fe59fb7c57297e710dd7b250320541b6"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stakpak/devx/releases/download/v0.4.35/devx_Linux_x86_64.tar.gz"
      sha256 "00221291f676bc1165f10df12a9259bdb4c946c01c1b9de3162b2128636174e8"

      def install
        bin.install "devx"
      end
    end
  end
end
