# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc ""
  homepage "https://devx.stakpak.dev/"
  version "0.4.38"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stakpak/devx/releases/download/v0.4.38/devx_Darwin_arm64.tar.gz"
      sha256 "d328e49fe9cba829a2817d9539aed9bba7f9417b92350d06accd175c7e4647f5"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stakpak/devx/releases/download/v0.4.38/devx_Darwin_x86_64.tar.gz"
      sha256 "b0fd1da9736a8110d22e58e7cc511afc1bd970838891038caefaf440a699efe4"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stakpak/devx/releases/download/v0.4.38/devx_Linux_arm64.tar.gz"
      sha256 "d99e53355b3d509d0c9dc4011634e92eaf244df001fb3a4cb7a4f558e1f2eeef"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stakpak/devx/releases/download/v0.4.38/devx_Linux_x86_64.tar.gz"
      sha256 "3e38398402667a34ca51463b6e42d8da0463f4f5b72a5447deae8e5942a20e24"

      def install
        bin.install "devx"
      end
    end
  end
end
