# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GukuDevx < Formula
  desc ""
  homepage "https://devx.guku.io/"
  version "0.3.27"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.3.27/guku-devx_Darwin_arm64.tar.gz"
      sha256 "3e8a919e77e0deb6f4d940f0bac72d23264b50ba72ba172d3a7af4f4eeae7814"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.3.27/guku-devx_Darwin_x86_64.tar.gz"
      sha256 "fa00a105e90a6c0c1c163411eed123fa92e301c2e249185b1440f05a1f34c029"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.3.27/guku-devx_Linux_x86_64.tar.gz"
      sha256 "e45ab4f5f5eba3db35fffee8394295e09db33715ea81cae40e9435ba299f79df"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.3.27/guku-devx_Linux_arm64.tar.gz"
      sha256 "90859988990dfa66299677cfc182506329fe799b7d8a089c0f50a2a5fb82d052"

      def install
        bin.install "devx"
      end
    end
  end
end
