# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GukuDevx < Formula
  desc ""
  homepage "https://devx.stakpak.dev/"
  version "0.4.25"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.4.25/guku-devx_Darwin_arm64.tar.gz"
      sha256 "df1b77a5e52025f7241c5cbb0e8084c4a38cdd9537c6f07a01451be60b2653be"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.4.25/guku-devx_Darwin_x86_64.tar.gz"
      sha256 "9e1ce3ae5951b240d6103fd8d780a68d6fd8b243dfe331ce2f8dad0b728f290b"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.4.25/guku-devx_Linux_arm64.tar.gz"
      sha256 "40e35734b9c524cacf14902667526005219f6d04847c9ed132eaf0511a33adce"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devopzilla/guku-devx/releases/download/v0.4.25/guku-devx_Linux_x86_64.tar.gz"
      sha256 "bbf90d6fc6b657555c99236d03e88ed38a0daef1ffc08be71eaf1b05ba24e79d"

      def install
        bin.install "devx"
      end
    end
  end
end
